/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author U S E R
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonKamar = new javax.swing.JButton();
        jButtonTamu = new javax.swing.JButton();
        jButtonReservasi = new javax.swing.JButton();
        jButtonPembayaran = new javax.swing.JButton();
        jButtonKaryawan = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hotel Management System");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login sebagai Administrator [ADMIN]");

        jButtonLogout.setBackground(new java.awt.Color(204, 0, 0));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(this::jButtonLogoutActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogout)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Selamat datang, Administrator!");

        jButtonKamar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButtonKamar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonKamar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKamar.setText("Kamar");
        jButtonKamar.addActionListener(this::jButtonKamarActionPerformed);

        jButtonTamu.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButtonTamu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTamu.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTamu.setText("Tamu");
        jButtonTamu.addActionListener(this::jButtonTamuActionPerformed);

        jButtonReservasi.setBackground(new java.awt.Color(204, 102, 255));
        jButtonReservasi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonReservasi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReservasi.setText("Reservasi");
        jButtonReservasi.addActionListener(this::jButtonReservasiActionPerformed);

        jButtonPembayaran.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPembayaran.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPembayaran.setText("Pembayaran");
        jButtonPembayaran.addActionListener(this::jButtonPembayaranActionPerformed);

        jButtonKaryawan.setBackground(new java.awt.Color(102, 102, 102));
        jButtonKaryawan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonKaryawan.setText("Karyawan");
        jButtonKaryawan.addActionListener(this::jButtonKaryawanActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonTamu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButtonReservasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
    LoginView login = new LoginView();
    login.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKamarActionPerformed
        // TODO add your handling code here:
            RoomView room = new RoomView();
            room.setVisible(true);
    }//GEN-LAST:event_jButtonKamarActionPerformed

    private void jButtonTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamuActionPerformed
        // TODO add your handling code here:
    GuestView guest = new GuestView();
    guest.setVisible(true);
    }//GEN-LAST:event_jButtonTamuActionPerformed

    private void jButtonReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservasiActionPerformed
        // TODO add your handling code here:
    ReservationView reservation = new ReservationView();
    reservation.setVisible(true);
    }//GEN-LAST:event_jButtonReservasiActionPerformed

    private void jButtonPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPembayaranActionPerformed
        // TODO add your handling code here:
    PaymentView payment = new PaymentView();
    payment.setVisible(true);
    }//GEN-LAST:event_jButtonPembayaranActionPerformed

    private void jButtonKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKaryawanActionPerformed
        // TODO add your handling code here:
    EmployeeView employee = new EmployeeView();
    employee.setVisible(true);
    }//GEN-LAST:event_jButtonKaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKamar;
    private javax.swing.JButton jButtonKaryawan;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonPembayaran;
    private javax.swing.JButton jButtonReservasi;
    private javax.swing.JButton jButtonTamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
