/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.EmployeeController;
import model.Employee;
import java.time.LocalDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author WIANDA
 */
public class EmployeView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeView.class.getName());
    private EmployeeController controller = new EmployeeController();
    private DefaultTableModel tableModel;
    private int selectedId = 0;
    private int currentPage = 1;
    /**
     * Creates new form EmployeView
     */
   public EmployeView() {

    initComponents();
    
    DateFormatter df = new DateFormatter(new SimpleDateFormat("yyyy-MM-dd"));
    df.setAllowsInvalid(false);
    jFormattedTextFieldHireD.setFormatterFactory(
    new DefaultFormatterFactory(df));

    tableModel = new DefaultTableModel();

    tableModel.addColumn("ID");
    tableModel.addColumn("Name");
    tableModel.addColumn("Email");
    tableModel.addColumn("Phone");
    tableModel.addColumn("Position");
    tableModel.addColumn("Salary");
    tableModel.addColumn("Hire Date");
    tableModel.addColumn("Status");

    jTableEmployee.setModel(tableModel);


    loadTable();
    clearForm();

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelHireDate = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelPosition = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldPhone = new javax.swing.JTextField();
        jTextFieldPosition = new javax.swing.JTextField();
        jTextFieldSalary = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jFormattedTextFieldHireD = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmployee = new javax.swing.JTable();
        jTextFieldCari = new javax.swing.JTextField();
        jButtonCari = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonBatal = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EMPLOYEE FORM");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Information"));

        jLabelName.setText("Name:");

        jLabel3.setText("Salary:");

        jLabelHireDate.setText("Hire Date (yyyy-MM-dd):");

        jLabel5.setText("Email:");

        jLabelPhone.setText("Phone:");

        jLabelPosition.setText("Position:");

        jLabelStatus.setText("Status:");

        jTextFieldName.addActionListener(this::jTextFieldNameActionPerformed);

        jTextFieldEmail.addActionListener(this::jTextFieldEmailActionPerformed);

        jTextFieldPhone.addActionListener(this::jTextFieldPhoneActionPerformed);

        jTextFieldPosition.addActionListener(this::jTextFieldPositionActionPerformed);

        jTextFieldSalary.addActionListener(this::jTextFieldSalaryActionPerformed);

        jTextFieldStatus.addActionListener(this::jTextFieldStatusActionPerformed);

        jFormattedTextFieldHireD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextFieldHireD.addActionListener(this::jFormattedTextFieldHireDActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(jTextFieldName)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPosition)
                            .addComponent(jLabelPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhone)
                            .addComponent(jTextFieldPosition))))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(jTextFieldSalary))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHireDate)
                            .addComponent(jLabelStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldHireD, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jTextFieldStatus))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelHireDate)
                                    .addComponent(jFormattedTextFieldHireD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPhone)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStatus)
                            .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPosition)
                    .addComponent(jTextFieldPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "null", "null", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmployee);

        jTextFieldCari.addActionListener(this::jTextFieldCariActionPerformed);

        jButtonCari.setText("Cari");
        jButtonCari.addActionListener(this::jButtonCariActionPerformed);

        jButtonAdd.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Simpan");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonEdit.setText("Ubah");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonBatal.setText("Batal");
        jButtonBatal.addActionListener(this::jButtonBatalActionPerformed);

        jButtonDelete.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonPrev.setText("<< Prev");
        jButtonPrev.addActionListener(this::jButtonPrevActionPerformed);

        jButtonNext.setText("Next >>");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCari)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jButtonPrev)
                .addGap(48, 48, 48)
                .addComponent(jButtonNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCari)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonBatal)
                    .addComponent(jButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrev)
                    .addComponent(jButtonNext))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTable() {

    tableModel.setRowCount(0);

    List<Employee> list = controller.getPage(currentPage);

    for (Employee e : list) {

        tableModel.addRow(new Object[]{
            e.getId(),
            e.getName(),
            e.getEmail(),
            e.getPhone(),
            e.getPosition(),
            e.getSalary(),
            e.getHireDate(),
            e.getStatus()
        });

    }

}
    
private void clearForm(){

    selectedId = 0;

    jTextFieldName.setText("");
    jTextFieldEmail.setText("");
    jTextFieldPhone.setText("");
    jTextFieldPosition.setText("");
    jTextFieldSalary.setText("");
    jFormattedTextFieldHireD.setText("");

    jTextFieldStatus.setText("");
    jTextFieldCari.setText("");

    jTableEmployee.clearSelection();

}
    
    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jTextFieldPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPositionActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    try {
        // Pastikan user sudah memilih data dari tabel
        if (selectedId == 0) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan diubah!");
            return;
        }
        
        if (jFormattedTextFieldHireD.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this,
            "Hire Date harus diisi (yyyy-MM-dd)");
    return;
}
        
        Employee e = new Employee();

        if (jTextFieldSalary.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Salary harus diisi");
    return;
}
        e.setId(selectedId);
        e.setName(jTextFieldName.getText());
        e.setEmail(jTextFieldEmail.getText());
        e.setPhone(jTextFieldPhone.getText());
        e.setPosition(jTextFieldPosition.getText());
        e.setSalary(Double.parseDouble(jTextFieldSalary.getText()));
        e.setHireDate(LocalDate.parse(jFormattedTextFieldHireD.getText()));
        e.setStatus(jTextFieldStatus.getText());

        int hasil = controller.update(e, selectedId);

        if (hasil > 0) {

            currentPage = 1;

            JOptionPane.showMessageDialog(this, "Data berhasil diubah");

            loadTable();

            clearForm();

        } else if (hasil == -1) {

            JOptionPane.showMessageDialog(this, "Data belum lengkap!");

        } else {

            JOptionPane.showMessageDialog(this, "Data gagal diubah!");

        }

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(this, "Salary harus berupa angka!");

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

    }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jTableEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmployeeMouseClicked
        // TODO add your handling code here:
        int row = jTableEmployee.getSelectedRow();

selectedId = Integer.parseInt(tableModel.getValueAt(row,0).toString());

jTextFieldName.setText(tableModel.getValueAt(row,1).toString());
jTextFieldEmail.setText(tableModel.getValueAt(row,2).toString());
jTextFieldPhone.setText(tableModel.getValueAt(row,3).toString());
jTextFieldPosition.setText(tableModel.getValueAt(row,4).toString());
jTextFieldSalary.setText(tableModel.getValueAt(row,5).toString());
jFormattedTextFieldHireD.setText(tableModel.getValueAt(row,6).toString());
jTextFieldStatus.setText(tableModel.getValueAt(row,7).toString());
    }//GEN-LAST:event_jTableEmployeeMouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSalaryActionPerformed

    private void jTextFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatusActionPerformed

    private void jTextFieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCariActionPerformed

    private void jButtonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCariActionPerformed
        // TODO add your handling code here:
        try{
    if (jTextFieldCari.getText().trim().isEmpty()) {

    JOptionPane.showMessageDialog(this, "Masukkan ID!");

    return;

}
    int id = Integer.parseInt(jTextFieldCari.getText());

    Employee e = controller.search(id);

    if(e!=null){

        selectedId = e.getId();
        currentPage = 1;

        jTextFieldName.setText(e.getName());
        jTextFieldEmail.setText(e.getEmail());
        jTextFieldPhone.setText(e.getPhone());
        jTextFieldPosition.setText(e.getPosition());
        jTextFieldSalary.setText(String.valueOf(e.getSalary()));
        jFormattedTextFieldHireD.setText(e.getHireDate().toString());
        jTextFieldStatus.setText(e.getStatus());

    }else{

        JOptionPane.showMessageDialog(this,"Data tidak ditemukan");

    }

}catch(Exception ex){

    JOptionPane.showMessageDialog(this,ex.getMessage());

}
    }//GEN-LAST:event_jButtonCariActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
    try {
        
        if(jTextFieldName.getText().trim().isEmpty()){

    JOptionPane.showMessageDialog(this,"Nama harus diisi");
    return;
}
        if (jFormattedTextFieldHireD.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this,
            "Hire Date harus diisi (yyyy-MM-dd)");
    return;
}
        Employee e = new Employee();
        
        if (jTextFieldSalary.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Salary harus diisi");
    return;
}
        e.setName(jTextFieldName.getText());
        e.setEmail(jTextFieldEmail.getText());
        e.setPhone(jTextFieldPhone.getText());
        e.setPosition(jTextFieldPosition.getText());
        e.setSalary(Double.parseDouble(jTextFieldSalary.getText()));
        e.setHireDate(LocalDate.parse(jFormattedTextFieldHireD.getText()));
        e.setStatus(jTextFieldStatus.getText());

        int hasil = controller.create(e);

        if (hasil > 0) {

            currentPage = 1;

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan");

            loadTable();

            clearForm();

        } else if (hasil == -1) {

            JOptionPane.showMessageDialog(this, "Data belum lengkap!");

        } else {

            JOptionPane.showMessageDialog(this, "Data gagal disimpan");

        }

    } catch (NumberFormatException ex) {

        JOptionPane.showMessageDialog(this, "Salary harus berupa angka!");

    } catch (Exception ex) {

        JOptionPane.showMessageDialog(this, ex.getMessage());

    }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_jButtonBatalActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if(selectedId==0){

    JOptionPane.showMessageDialog(this,"Pilih data terlebih dahulu");
    return;

}

int hasil = controller.delete(selectedId);

if (hasil > 0) {

    currentPage = 1;

    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

    loadTable();

    clearForm();

} else {

    JOptionPane.showMessageDialog(this, "Data gagal dihapus");

}
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
        
    if(currentPage > 1){

        currentPage--;

        loadTable();

    }
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
            currentPage++;

    loadTable();

    if(tableModel.getRowCount()==0){

        currentPage--;

        loadTable();

    }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jFormattedTextFieldHireDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHireDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldHireDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBatal;
    private javax.swing.JButton jButtonCari;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JFormattedTextField jFormattedTextFieldHireD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelHireDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPosition;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmployee;
    private javax.swing.JTextField jTextFieldCari;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldSalary;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables
}
