/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.RoomController;
import model.Room;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author U S E R
 */
public class RoomView extends javax.swing.JFrame {
    
     private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RoomView.class.getName());
     private Integer selectedId = null;
     private RoomController controller = new RoomController();
     private int currentPage = 1;
     private int totalPage = 1;
     private final int limit = 5;

    public RoomView() {
    initComponents();
    jComboBoxRoomType.removeAllItems();
    jComboBoxRoomType.addItem("Standard");
    jComboBoxRoomType.addItem("Deluxe");
    jComboBoxRoomType.addItem("Suite");
    jComboBoxRoomType.addItem("Family");

    jComboBoxStatus.removeAllItems();
    jComboBoxStatus.addItem("AVAILABLE");
    jComboBoxStatus.addItem("OCCUPIED");
    jComboBoxStatus.addItem("MAINTENANCE");
    loadRoomData();
}
    
    private void loadRoomData() {

    int totalData = controller.count();
    totalPage = (int) Math.ceil((double) totalData / limit);

    if (totalPage == 0) {
        totalPage = 1;
    }

    if (currentPage > totalPage) {
        currentPage = totalPage;
    }

    List<Room> rooms = controller.getPage(currentPage);

    String data[][] = new String[rooms.size()][7];

    for (int i = 0; i < rooms.size(); i++) {

        data[i][0] = String.valueOf(rooms.get(i).getId());
        data[i][1] = rooms.get(i).getRoomNumber();
        data[i][2] = rooms.get(i).getRoomType();
        data[i][3] = String.valueOf(rooms.get(i).getPricePerNight());
        data[i][4] = rooms.get(i).getStatus();
        data[i][5] = String.valueOf(rooms.get(i).getCapacity());
        data[i][6] = rooms.get(i).getDescription();
    }

    String column[] = {
        "ID",
        "No. Kamar",
        "Tipe",
        "Harga",
        "Status",
        "Kapasitas",
        "Deskripsi"
    };

    jTableRoom.setModel(new javax.swing.table.DefaultTableModel(data, column));

    jButtonPrev.setEnabled(currentPage > 1);
    jButtonNext.setEnabled(currentPage < totalPage);
}
 
    private void clearForm() {

    selectedId = null;

    jTextFieldRoomNumber.setText("");
    jTextFieldPricePerNight.setText("");
    jTextFieldCapacity.setText("");
    jTextAreaDescription.setText("");

    jComboBoxRoomType.setSelectedIndex(0);
    jComboBoxStatus.setSelectedIndex(0);

    jTextFieldRoomNumber.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRoomNumber = new javax.swing.JTextField();
        jComboBoxRoomType = new javax.swing.JComboBox<>();
        jTextFieldPricePerNight = new javax.swing.JTextField();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCapacity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jButtonCancel = new javax.swing.JButton();
        jTextFieldSearchId = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jButtonPrev = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Form Kamar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Kamar"));

        jLabel2.setText("No. Kamar:");

        jLabel3.setText("Tipe Kamar:");

        jLabel4.setText("Harga per malam (Rp):");

        jLabel5.setText("Status:");

        jTextFieldRoomNumber.addActionListener(this::jTextFieldRoomNumberActionPerformed);

        jComboBoxRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRoomType.addActionListener(this::jComboBoxRoomTypeActionPerformed);

        jTextFieldPricePerNight.addActionListener(this::jTextFieldPricePerNightActionPerformed);

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxStatus.addActionListener(this::jComboBoxStatusActionPerformed);

        jButtonSave.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButtonSave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSave.setText("Simpan");
        jButtonSave.addActionListener(this::jButtonSaveActionPerformed);

        jButtonUpdate.setText("Ubah");
        jButtonUpdate.addActionListener(this::jButtonUpdateActionPerformed);

        jButtonDelete.setBackground(new java.awt.Color(204, 0, 0));
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Hapus");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jLabel6.setText("Kapasitas:");

        jTextFieldCapacity.addActionListener(this::jTextFieldCapacityActionPerformed);

        jLabel7.setText("Deskripsi:");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane3.setViewportView(jTextAreaDescription);

        jButtonCancel.setText("Batal");
        jButtonCancel.addActionListener(this::jButtonCancelActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPricePerNight, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxRoomType, javax.swing.GroupLayout.Alignment.LEADING, 0, 230, Short.MAX_VALUE)
                    .addComponent(jTextFieldRoomNumber, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCapacity)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonUpdate)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonDelete))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jComboBoxRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldPricePerNight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonUpdate)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonCancel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addComponent(jButtonDelete)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTextFieldSearchId.setText("Masukkan ID");
        jTextFieldSearchId.addActionListener(this::jTextFieldSearchIdActionPerformed);

        jButtonSearch.setText("Cari");
        jButtonSearch.addActionListener(this::jButtonSearchActionPerformed);

        jTableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title1", "Title2", "Title3", "Tiltle4", "null", "null", "Title 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRoomMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableRoom);

        jButtonPrev.setText("<< Prev");
        jButtonPrev.addActionListener(this::jButtonPrevActionPerformed);

        jButtonNext.setText("Next >>");
        jButtonNext.addActionListener(this::jButtonNextActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearch)
                                .addGap(250, 250, 250))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPrev)
                        .addGap(72, 72, 72)
                        .addComponent(jButtonNext)
                        .addGap(189, 189, 189))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPrev)
                    .addComponent(jButtonNext))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSearchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchIdActionPerformed
        // TODO add your handling code here:
    jButtonSearchActionPerformed(evt);
    }//GEN-LAST:event_jTextFieldSearchIdActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
           clearForm();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here:
        try {
        Room room = new Room();

        room.setRoomNumber(jTextFieldRoomNumber.getText().trim());
        room.setRoomType(jComboBoxRoomType.getSelectedItem().toString());
        room.setPricePerNight(Double.parseDouble(jTextFieldPricePerNight.getText()));
        room.setStatus(jComboBoxStatus.getSelectedItem().toString());
        room.setCapacity(Integer.parseInt(jTextFieldCapacity.getText()));
        room.setDescription(jTextAreaDescription.getText());

        int result;

        if (selectedId == null) {
            result = controller.create(room);
        } else {
            result = controller.update(room, selectedId);
        }

        if (result == 1) {

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan.");
            clearForm();
            loadRoomData();

        } else {

            JOptionPane.showMessageDialog(this, "Data gagal disimpan.");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldRoomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRoomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRoomNumberActionPerformed

    private void jComboBoxRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoomTypeActionPerformed

    private void jTextFieldPricePerNightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPricePerNightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPricePerNightActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jTextFieldCapacityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCapacityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCapacityActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
            if (selectedId == null) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu.");
        return;
    }
    jButtonSaveActionPerformed(evt);
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedId == null) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin menghapus data?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {

        int result = controller.delete(selectedId);

        if (result == 1) {
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            clearForm();
            loadRoomData();
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal dihapus.");
        }

     }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
            try {

        int id = Integer.parseInt(jTextFieldSearchId.getText());

        Room room = controller.search(id);

        if (room != null) {

            selectedId = room.getId();

            jTextFieldRoomNumber.setText(room.getRoomNumber());
            jComboBoxRoomType.setSelectedItem(room.getRoomType());
            jTextFieldPricePerNight.setText(String.valueOf(room.getPricePerNight()));
            jComboBoxStatus.setSelectedItem(room.getStatus());
            jTextFieldCapacity.setText(String.valueOf(room.getCapacity()));
            jTextAreaDescription.setText(room.getDescription());

        } else {

            JOptionPane.showMessageDialog(this, "Data tidak ditemukan.");

        }

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(this, "ID harus berupa angka.");

    }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRoomMouseClicked
        // TODO add your handling code here:
      int row = jTableRoom.getSelectedRow();

    if (row == -1) {
        return;
    }

    selectedId = Integer.parseInt(jTableRoom.getValueAt(row, 0).toString());

    jTextFieldRoomNumber.setText(jTableRoom.getValueAt(row, 1).toString());
    jComboBoxRoomType.setSelectedItem(jTableRoom.getValueAt(row, 2).toString());
    jTextFieldPricePerNight.setText(jTableRoom.getValueAt(row, 3).toString());
    jComboBoxStatus.setSelectedItem(jTableRoom.getValueAt(row, 4).toString());
    jTextFieldCapacity.setText(jTableRoom.getValueAt(row, 5).toString());
    jTextAreaDescription.setText(jTableRoom.getValueAt(row, 6).toString());
    }//GEN-LAST:event_jTableRoomMouseClicked

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
        if (currentPage > 1) {
        currentPage--;
        loadRoomData();
    }
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        if (currentPage < totalPage) {
        currentPage++;
        loadRoomData();
    }
    }//GEN-LAST:event_jButtonNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RoomView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxRoomType;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableRoom;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldCapacity;
    private javax.swing.JTextField jTextFieldPricePerNight;
    private javax.swing.JTextField jTextFieldRoomNumber;
    private javax.swing.JTextField jTextFieldSearchId;
    // End of variables declaration//GEN-END:variables
}
